# Generated by Django 3.2.5 on 2021-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210704_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamap',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='datamap',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
