# Generated by Django 3.2.5 on 2021-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210704_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamap',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='geoinfo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='kindergartens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='parks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='shools',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datamap',
            name='stores',
            field=models.IntegerField(default=0),
        ),
    ]
